"""Add priority field to WorkOrder

Revision ID: 281c5905b65a
Revises: 
Create Date: 2024-10-11 14:14:25.284358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281c5905b65a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_critical', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_column('is_critical')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
